version: '3.8'
services:
   web:
       build: .
       command: bash -c "
         cd stripe_app/
         && python manage.py makemigrations
         && python manage.py migrate
         && export DJANGO_SUPERUSER_USERNAME=$${DJANGO_SUPERUSER_USERNAME}
         && export DJANGO_SUPERUSER_EMAIL=$${DJANGO_SUPERUSER_EMAIL}
         && export DJANGO_SUPERUSER_PASSWORD=$${DJANGO_SUPERUSER_PASSWORD}
         && python manage.py createsuperuser --noinput
         && python manage.py runserver 0.0.0.0:8000
         "
       ports:
           - 8000:8000
       env_file:
         - ./.env