# Generated by Django 2.2.19 on 2022-09-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20220913_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(verbose_name='Номер заказа'),
        ),
    ]
